### ISSUE TITLE
optionModelClass in translations

### ISSUE THREAD

**Issue by rokorolov** [yii2tech/ar-variation#14]
I'm make a module that knows nothing about optionModelClass because gets this keys in params. In order an user was able to solve from where set languages params. The module only knows that he should translate into languages in the given parameters.
Is there a possibility not to use optionModelClass?
Or it is not good practice, because keys can be changed and if using MySQL can solve this automatically with FOREIGN KEY - ON UPDATE CASCADE?

**Comment by klimov-paul** [comment]
No, that is impossible.
`optionModelClass` is crucial, since it provides ability to verify if all variation models are initialized, handles situation when new variation option appears, which variation has not been saved before and so on.

However you can mock up result for variation models query using following extension:
https://github.com/yii2tech/filedb
